name: mangocat
favicon: null
layout_spectrum: 0.6555755734443665
typography_spectrum: 0.024847968947142363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06915525021031499
  lightness: 0.8323976348619908
  saturation: 0.14524038275703788
  rhythmicContrast: 0.7827777478378266
purpose: []
