typography_spectrum: 0.47424
color:
  brandColors:
    - '#ffffff'
    - '#b5282d'
    - '#181339'
    - '#436a3d'
    - '#ef7045'
  brandStrength: 0.06915525021031499
  lightness: 0.8323976348619908
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.43285
analytics:
  google: null
  facebook: null
  twitter: null
name: mangocat
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: hello
purpose: []
