name: mangocat
favicon: null
layout_spectrum: 0.43285
typography_spectrum: 0.47424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5282d'
    - '#181339'
    - '#436a3d'
    - '#ef7045'
  brandStrength: 0.06915525021031499
  lightness: 0.8323976348619908
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
